#pragma once

const unsigned short g_nBackCX = 800;
const unsigned short g_nBackCY = 600;

const float		g_fDefaultRimLight = 0.1f;


enum SCENEID {SCENE_STATIC, SCENE_LOGO, SCENE_STAGE, SCENE_END};
enum CAMETATYPE { CAMERA_DEFAULT, CAMERA_STATIC, CAMERA_DYANMIC, CAMERA_CUTSCENE, CAMERA_END };
enum PLAYERTYPE{PLAYER_LUPS, PLAYER_SIRE, /*PLAYER_MASQ,*/ PLAYER_END};
enum PLAYERCAMERA_TYPE{ PLAYERCAMERA_DEFAULT, PLAYERCAMERA_MIDDLE, PLAYERCAMERA_OUT, PLAYERCAMERA_END};
enum COMBATSTATE{GENERAL,COMBAT};
enum CONTROLTYPE{CONTROL_PLAYER, CONTROL_AI, CONTROL_END};
enum COLLISION_TARGET{	COL_PLAYER, COL_MONSTER, COL_END};
enum OBJECTTYPE{	MESH_DYNAMIC, MESH_STATIC, OBJ_EFFECT, MESH_END};
enum EFFECTTYPE {EFFECT_NULL = 0, EFFECT_BLOOD, EFFECT_FIRE, EFFECT_EXCLAMATIONMARK, EFFECT_HEAL};
enum STAGE { LOGO, STAGE1, STAGE2 };

extern HINSTANCE g_hInst;
extern HWND g_hWnd;
extern bool	g_bDebug;
extern bool g_bDefferd;

#define	STAGE1_VTXCNTX 129
#define	STAGE1_VTXCNTZ 129
#define STAGE1_VTXITV 1

#define	STAGE2_VTXCNTX 257
#define	STAGE2_VTXCNTZ 257
#define STAGE2_VTXITV 1

#define COOLDOWN_END 3
#define	SCENE_CHANGE 100


