//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Tool.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_ToolTYPE                    130
#define IDD_CONTROLFORM                 310
#define IDD_TERRAIN                     311
#define IDD_EFFECT                      312
#define IDD_MESH                        313
#define IDD_CAMERA                      314
#define IDD_NAVIMESH                    315
#define IDD_ANIMATION                   316
#define IDD_UNIT                        319
#define IDD_UI                          320
#define IDD_LIGHT                       321
#define IDC_TAB1                        1000
#define IDC_TREE1                       1002
#define IDC_EDIT1                       1003
#define IDC_TREE2                       1003
#define IDC_EDIT2                       1004
#define IDC_TREE3                       1004
#define IDC_EDIT3                       1005
#define IDC_EDIT4                       1006
#define IDC_EDIT5                       1007
#define IDC_CAMERA_TAG                  1007
#define IDC_EDIT_COL_POS_Z              1007
#define IDC_EDIT6                       1008
#define IDC_EDIT_COL_RADIUS             1008
#define IDC_SLIDER1                     1009
#define IDC_EDIT_COL_RADIUS2            1009
#define IDC_EDIT_COLLIDER_TAG           1009
#define IDC_BUTTON1                     1010
#define IDC_BUTTON2                     1011
#define IDC_RADIO1                      1012
#define IDC_BUTTON4                     1012
#define IDC_BUTTON3                     1013
#define IDC_RADIO2                      1013
#define IDC_BUTTON5                     1013
#define IDC_OBJECTTREE                  1014
#define IDC_BUTTON6                     1014
#define IDC_BUTTON7                     1015
#define IDC_RADIO3                      1016
#define IDC_BUTTON8                     1016
#define IDC_RADIO4                      1017
#define IDC_BUTTON9                     1017
#define IDC_RADIO5                      1018
#define IDC_RADIO6                      1019
#define IDC_RADIO7                      1020
#define IDC_RADIO8                      1021
#define IDC_OBJECTTREE2                 1022
#define IDC_RADIO9                      1022
#define IDC_RADIO10                     1023
#define IDC_RADIO_ROTATION              1023
#define IDC_SCALE_X                     1024
#define IDC_POSITION                    1025
#define IDC_LIST1                       1026
#define IDC_POSITION_X                  1029
#define IDC_ROTATION_X                  1030
#define IDC_RADIO_SCALE                 1031
#define IDC_SCALE_Y                     1032
#define IDC_SPIN_SCALE_X                1033
#define IDC_ROTATION_Y                  1034
#define IDC_CAMERA_SAVE                 1034
#define IDC_POSITION_Y                  1035
#define IDC_CAMERA_LOAD                 1035
#define IDC_SCALE_Z                     1036
#define IDC_CAMERA_CREATE               1036
#define IDC_CAMERA_DELETE               1037
#define IDC_ROTATION_Z                  1038
#define IDC_TREE_CUTSCENE               1038
#define IDC_POSITION_Z                  1039
#define IDC_CAMERA_ADD                  1039
#define IDC_CAMERA_ADDPOINT             1039
#define IDC_SPIN_SCALE_Y                1040
#define IDC_CAMERA_APPLY                1040
#define IDC_SPIN_SCALE_Z                1041
#define IDC_CANERA_PLAY                 1041
#define IDC_SPIN_ROTATION_X             1042
#define IDC_CAMERA_STOP                 1042
#define IDC_SPIN_ROTATION_Y             1043
#define IDC_UI_SAVE                     1043
#define IDC_CAMERA_SPEED_APPLY          1043
#define IDC_SPIN_ROTATION_Z             1044
#define IDC_UI_LOAD                     1044
#define IDC_UI_FRAME_CREATE             1045
#define IDC_UI_CREATE                   1046
#define IDC_UI_FRAME_EDIT               1047
#define IDC_SPIN_POSITION_X             1048
#define IDC_UI_EDIT                     1048
#define IDC_SPIN_POSITION_Y             1049
#define IDC_UI_SCALEX_EDIT              1049
#define IDC_SPIN_POSITION_Z2            1050
#define IDC_UI_SCALEY_EDIT              1050
#define IDC_UI_POSITIONX_EDIT           1051
#define IDC_UI_POSITIONY_EDIT           1052
#define IDC_UI_Rotation                 1053
#define IDC_UI_DEPTHZ                   1054
#define IDC_TREE_UI_List                1055
#define IDC_TREE_UI_TEXTURE_LIST        1056
#define IDC_EDIT_COL_POS_X              1057
#define IDC_UI_CREATE2                  1057
#define IDC_UI_CHANGE                   1057
#define IDC_EDIT_COL_POS_Y              1058
#define IDC_UI_CHANGE2                  1058
#define IDC_UIFrame_CHANGE              1058
#define IDC_COL_LIST                    1059
#define IDC_BT_CREATE_COL               1060
#define IDC_BT_DELETE_COL               1061
#define IDC_BT_SAVE                     1062
#define IDC_BT_CREATE_LOAD              1063
#define IDC_SPIN_COL_POS_X              1064
#define IDC_SPIN_COL_POS_Y              1065
#define IDC_SPIN_COL_POS_Z              1066
#define IDC_SPIN_COL_POS_X2             1067
#define IDC_SPIN_COL_RADIUS             1067
#define IDC_MESH_FRAME_LIST             1068
#define IDC_SLIDER_SCALE_X              1069
#define IDC_BT_TRANSFORM_APPLY          1070
#define IDC_BT_PAREENT_APPLY            1071
#define IDC_BT_TRANSFORM_APPLY2         1071
#define IDC_BT_LAYERTAG                 1071
#define IDC_SLIDER_SCALE_Y              1072
#define IDC_BT_DELETE                   1072
#define IDC_EDIT_DYANMIC_LAYER          1074
#define IDC_BT_SAVE_DYNAMIC             1075
#define IDC_BT_LOAD_DYANMIC             1076
#define IDC_EDIT_CUTSCENE_SPEED         1077
#define IDC_UI_DELETE                   1078
#define IDC_CREATE_GROUP                1080
#define IDC_CREATE_RECT                 1081
#define IDC_CREATE_MESH2                1082
#define IDC_CREATE_MESH                 1082
#define IDC_CHECK_PASS0                 1084
#define IDC_CHECK_PASS1                 1085
#define IDC_CHECK_PASS2                 1086
#define IDC_EDIT_USPEED                 1087
#define IDC_EDIT_USPEED2                1088
#define IDC_EDIT_VSPEED                 1088
#define IDC_CHECK_PASS3                 1089
#define IDC_BT_UVANIMATION_APPLY        1090
#define IDC_CREATE_PARTICLE             1091
#define IDC_EDIT_THETA                  1092
#define IDC_EDIT_PHI                    1093
#define IDC_EDIT_SPEEDSCALE             1094
#define IDC_EDIT_INIT_SPEED             1094
#define IDC_BT_PARTICLE_INFO_ALLPY      1095
#define IDC_LIST_MESH                   1096
#define IDC_EFFECT_SAVE                 1097
#define IDC_EDIT_INIT_ACC_X             1098
#define IDC_EDIT_INIT_ACC_Y             1099
#define IDC_EDIT_INIT_ACC_Z             1100
#define IDC_BT_S_POSITION_SET           1101
#define IDC_BT_E_POSITION_SET           1102
#define IDC_EDIT_LEFT_TIME              1103
#define IDC_EDIT_INIT_LIFETIME          1103
#define IDC_EDIT_FRAME_CONST            1104
#define IDC_LIST_RECT                   1105
#define IDC_LIST_PARTICLE               1106
#define IDC_EFFECT_Load                 1107
#define IDC_BT_TIME_SET                 1108
#define IDC_EDIT_MIN_PHI                1108
#define IDC_EDIT_POSITION_START_TIME    1109
#define IDC_EDIT_SPEED_RANGE            1109
#define IDC_EDIT_POSITION_END_TIME      1110
#define IDC_EDIT_LIFETIME_RANGE         1110
#define IDC_EDIT_POSITION_START_POSITION_X 1111
#define IDC_EDIT_POSITION_START_POSITION_Y 1112
#define IDC_EDIT_POSITION_START_POSITION_Z 1113
#define IDC_EDIT_POSITION_END_POSITION_X 1114
#define IDC_EDIT_POSITION_END_POSITION_Y 1115
#define IDC_EDIT_POSITION_END_POSITION_Z 1116
#define IDC_EDIT_LIFE_TIME              1117
#define IDC_EDIT_ALPHA_WIDTH            1117
#define IDC_BT_PLAY                     1118
#define IDC_BT_STOP                     1119
#define IDC_BT_PAUSE                    1120
#define IDC_BT_S_ROTATION_SET           1121
#define IDC_BT_E_ROTATION_SET           1122
#define IDC_BT_ROTATION_TIME_SET        1123
#define IDC_EDIT_ALPHA_HEIGHT           1123
#define IDC_EDIT_ROTATION_START_TIME    1124
#define IDC_EDIT_BASE_WIDTH             1124
#define IDC_EDIT_ROTATION_END_TIME      1125
#define IDC_EDIT_USPEED6                1125
#define IDC_EDIT_BASE_HEIGHT            1125
#define IDC_EDIT_ROTATION_START_POSITION_X 1126
#define IDC_EDIT_ROTATION_START_POSITION_Y 1127
#define IDC_EDIT_ROTATION_START_POSITION_Z 1128
#define IDC_EDIT_ROTATION_END_POSITION_X 1129
#define IDC_EDIT_ROTATION_END_POSITION_Y 1130
#define IDC_EDIT_ROTATION_END_POSITION_Z 1131
#define IDC_BT_S_SCALE_SET              1132
#define IDC_BT_E_SCALE_SET              1133
#define IDC_BT_TIME_SCALE_SET           1134
#define IDC_MESH_TAG_BT                 1134
#define IDC_EDIT_SCALE_START_TIME       1135
#define IDC_EDIT_SCALE_END_TIME         1136
#define IDC_EDIT_SCALE_START_POSITION_X 1137
#define IDC_EDIT_SCALE_START_POSITION_Y 1138
#define IDC_EDIT_SCALE_START_POSITION_Z 1139
#define IDC_EDIT_SCALE_END_POSITION_X   1140
#define IDC_EDIT_SCALE_END_POSITION_Y   1141
#define IDC_EDIT_SCALE_END_POSITION_Z   1142
#define IDC_EDIT_MIN_THETA              1143
#define IDC_EDIT_TAG                    1144
#define IDC_EDIT_PARTICLENUM            1145
#define IDC_EDIT_FADEIN                 1146
#define IDC_EDIT_FADEOUT                1147
#define IDC_EDIT_EFFECT_GROUP           1148
#define IDC_EDIT_GROUPEFFECT_LIEFTIME   1149
#define IDC_BT_GROUPEFFECT_LIFETIME_APPLY 1150
#define IDC_EDIT_STARTTIME              1151
#define IDC_EDIT_ENTIME                 1152
#define IDC_BT_EFFECT_DELETE_PARTICLE   1153
#define IDC_BT_EFFECT_DELETE_RECT       1154
#define IDC_BT_EFFECT_DELETE_MESH       1155
#define IDC_BT_SELECT_CLEAR             1156
#define IDC_CHECK_RECYCLE               1157
#define IDC_EDIT_ALPHA                  1158
#define IDC_EDIT_ALPHA2                 1159
#define IDC_EDIT_INIT_ALPHA             1159
#define IDC_BT_SET_TAG                  1160
#define IDC_LIGHT_LIST                  1161
#define IDC_CHECK_PASS4                 1161
#define IDC_EDIT_LIGHT_POSITION_X       1162
#define IDC_EDIT_LIGHT_POSITION_Y       1163
#define IDC_EDIT_LIGHT_POSITION_Z       1164
#define IDC_BT_LIGHT_APPLY              1165
#define IDC_LIGHT_SAVE                  1166
#define IDC_LIGHT_LOAD                  1167
#define IDC_EDIT_LIGHT_DIFFUSE_R        1168
#define IDC_EDIT_LIGHT_DIFFUSE_G        1169
#define IDC_EDIT_LIGHT_DIFFUSE_B        1170
#define IDC_EDIT_LIGHT_DIFFUSE_A        1171
#define IDC_EDIT_LIGHT_AMBIENT_R        1172
#define IDC_EDIT_LIGHT_AMBIENT_G        1173
#define IDC_EDIT_LIGHT_AMBIENT_B        1174
#define IDC_EDIT_LIGHT_AMBIENT_A        1175
#define IDC_EDIT_LIGHT_SPECULAR_R       1176
#define IDC_EDIT_LIGHT_SPECULAR_G       1177
#define IDC_EDIT_LIGHT_SPECULAR_B       1178
#define IDC_EDIT_LIGHT_SPECULAR_A       1179
#define IDC_EDIT_LIGHT_RAGNE            1180
#define IDC_BT_LIGHT_CREATE             1181
#define IDC_BT_LIGHT_CREATE2            1182
#define IDC_BT_LIGHT_DELETE             1182
#define IDC_EDIT_MESH_TAG               1183
#define IDC_EDIT_POSITION_X             1184
#define IDC_EDIT_POSITION_Y             1185
#define IDC_EDIT_POSITION_Z             1186

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        323
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1187
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
